os: osx
language: swift
osx_image: xcode11.2
script:
    - xctool -workspace fraise.xcworkspace -scheme Pods-fraise run-tests
    - xcodebuild clean -workspace fraise.xcworkspace -scheme Pods-fraise -destination "platform=iOS Simulator,name=iPhone 11,OS=13.1" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet