os: osx
language: swift
osx_image: xcode11.2
script:
    - xctool -workspace fraise.xcworkspace -scheme Pods-fraise run-tests
    - xcodebuild clean build -workspace fraise.xcworkspace -scheme Pods-fraise -destination generic/platform=iOS CODE_SIGN_IDENTITY=""  CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet